version: "3.6"
services:
  api:
    image: mtijnnl/api:1.0
    depends_on:
      - postgres
    networks:
      - traefik_web
      - api_internal
    volumes:
      - /opt/api/config:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.martijnklene.nl`)
      - traefik.http.routers.api.entrypoints=https
      - traefik.http.services.api.loadbalancer.server.port=8080
      - traefik.http.routers.presentations.tls=true
      - traefik.http.routers.presentations.tls.certresolver=default

  postgres:
    image: postgres:10.7-alpine
    networks:
      - api_internal
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  traefik_web:
    external: true
  api_internal:

volumes:
  postgres:
