version: "3.6"
services:
  blog:
    image: mtijnnl/api:latest
    networks:
      - traefik_web
    secrets:
      - secret_thing
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.blog.rule=Host(`api.martijnklene.nl`)
        - traefik.http.routers.blog.entrypoints=https
        - traefik.http.services.blog.loadbalancer.server.port=8080
        - traefik.http.routers.blog.tls=true
        - traefik.docker.network=traefik_web

networks:
  traefik_web:
    external: true
  api_internal:

secrets:
  secret_thing:
    external: true
