version: "3.6"
services:
  web:
    image: registry.martijnklene.nl/mtijnnl/api:latest
    depends_on:
      - postgres
    networks:
      - traefik_web
    volumes:
      - /opt/api/config:/usr/share/api/config
  postgres:
    environment:
      POSTGRES_PASSWORD: /run/secrets/database.password
      POSTGRES_USER: /run/secrets/database.username
    secrets:
      - database.username
      - database.password

networks:
  traefik_web:
    external: true

secrets:
  database.username:
    external: true
  database.password:
    external: true