version: "3.6"
services:
  web:
    image: mtijnnl/api:snapshot
    ports:
      - 8080:8080
    volumes:
      - ./config:/config
    depends_on:
      - postgres
    networks:
      - internal
  postgres:
    image: postgres
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d/
      - /data/api/database:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal: