version: "3.6"
services:
  web:
    volumes:
      - ./config:/usr/share/api/config
  postgres:
    ports:
      - 5432:5432
    volumes:
      - /data/api/database:/var/lib/postgresql/data

networks:
  internal:
    external: false
    ipam:
      driver: default
      config:
        - subnet: 172.40.4.0/24