version: "3.6"
services:
  web:
    image: mtijnnl/api:1.0
    depends_on:
      - postgres
    networks:
      - traefik_web
      - api_internal
    volumes:
      - /opt/api/config:/config
    deploy:
      labels:
        traefik.enable: "true"
        traefik.portainer.port: "8080"
        traefik.docker.network: "traefik_web"
        traefik.frontend.rule: "Host:api.martijnklene.nl"
        traefik.frontend.entryPoints: "https"
        traefik.frontend.redirect.entryPoint: "https"

  postgres:
    image: postgres:10.7-alpine
    networks:
      - api_internal
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  traefik_web:
    external: true
  api_internal:

volumes:
  postgres:
