# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/src

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - setup_remote_docker
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn -s ~/src/.circleci/settings.xml clean package
      - store_test_results:
          path: target/surefire-reports
  publish:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push mtijnnl/api

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: docker
      - publish:
          requires:
            - build
        context: docker